apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-list-app
  labels:
    app: product-list-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-list-app
  template:
    metadata:
      labels:
        app: product-list-app
    spec:
      containers:
        - name: product-list-app
          image: anupkrishna2000/product-list-app:v1
          ports:
            - containerPort: 5070
          env:
            - name: FLASK_ENV
              value: "production"
