apiVersion: v1
kind: Service
metadata:
  name: product-list-service
spec:
  selector:
    app: product-list-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5070
  type: LoadBalancer
